name:                hamp-free
version:             0.1.0.0
github:              "pinselimo/hamp-free"
license:             AGPL-3.0
author:              "Simon Plaklb"
maintainer:          "s.plakolb@gmail.com"
copyright:           "2020 Simon Plaklb"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pinselimo/hamp-free#readme>

dependencies:
- base >= 4.8
- random >=1.1 && <1.2
- filepath >=1.4 && <1.5
- bytestring >=0.10 && <0.11
- directory >=1.2
- process >=1.2
- network >=3.0
- containers >=0.5
- parsec >=3.1 && <3.2

library:
  source-dirs: src

executables:
  hamp-free-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamp-free

tests:
  hamp-free-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamp-free
